apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
         image: httpd:2
         ports:
           - containerPort: 80
  selector:
    matchlabels:
      app: httpd
