version: '3'
services:
  webservice:
    build:
      context: "/home/ec2-user"
      dockerfile: "Dockerfile.httpd"
    ports:
      - "80:80"
  appservice:
    build:
      context: "."
      dockerfile: "Dockerfile.tomcat"
    ports:
      - "8080:8080"
