version: '3'
services:
  fe:
    build:
      context: "."
      dockerfile: "Dockerfile"
    ports:
      - "80:8080"
  be:
    build:
      context: "/home/ec2-user"
      dockerfile: "Dockerfile.httpd"
    ports:
      - "90:80"
