# services:
#   fe:
#     build:
#       context: "."
#       dockerfile: "Dockerfile"
#     ports:
#       - "80:8080"
#   be:
#     build:
#       context: "."
#       dockerfile: "Dockerfile.httpd"
#     ports:
#       - "90:80"


version: '3.8'
services:
  fe:
    build:
      context: "."
      dockerfile: "Dockerfile"
    ports:
      - "80:8080"
  be:
    build:
      context: "."
      dockerfile: "Dockerfile.httpd"
    ports:
      - "90:80"
