apiVersion: apps/v1
kind: Deployment
metadata:
  name: docuhubimg-httpd
  labels:
    app: httpd
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: image:1.0
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: httpd
